data_path: dataset_saves
dataset_config_path: configs/dataset/hpo_config.yaml

save:
  directory: results
  run_name: HPO

# ezek lehet jók később ha d-p-re fókuszálunk
# evaluation_entity_whitelist:
# evaluation_relation_whitelist:

# 2. Model
model: RotatE
model_kwargs:
  embedding_dim: 512
# 3. Loss
loss: MarginRankingLoss # ez a default az összes modellnél amit néztem
loss_kwargs:
  margin: 3.0
# 4. Regularizer
regularizer: 
regularizer_kwargs:
# 5. Optimizer
optimizer: Adam
optimizer_kwargs:
  lr: 0.002
clear_optimizer:
# 5.1 Learning Rate Scheduler
lr_scheduler: ExponentialLR
lr_scheduler_kwargs:
  gamma: 0.9
# 6. Training Loop
training_loop: 
training_loop_kwargs:
negative_sampler: BernoulliNegativeSampler # BasicNegativeSampler, PseudoTypedNegativeSampler
negative_sampler_kwargs:
  num_negs_per_pos: 50
# 7. Training
epochs: 100
training_kwargs:
  batch_size: 1024
  checkpoint_name: checkpoint.pth
  checkpoint_frequency: 5
  checkpoint_on_failure: True
stopper: "early"
stopper_kwargs:
  frequency: 5
  patience: 3
  relative_delta: 0.002

# 8. Evaluation
evaluator: 
evaluator_kwargs:
evaluation_kwargs:
  batch_size: 128
# 9. Tracking
result_tracker: "wandb"
result_tracker_kwargs:
  project: RotatE_HPO
# Misc
# metadata: 
# device: "cuda"
random_seed: 42
# use_testing_data: True
# evaluation_fallback: True
# filter_validation_when_testing:  True
# use_tqdm: True
