kg_path: "primekg/kg.csv"

key: "name" # "index" or "name"

drop_duplicates: true
remove_self_loops: true

inverse_relations: True

val_count: 10000
test_count: 10000
random_seed: 42

# not working yet
features:
#   enabled: true

relation_types:
  # Disease-centric
  - disease_disease
  - disease_protein
  - disease_phenotype_positive
  - disease_phenotype_negative

  # Drug-centric
  - drug_drug
  - drug_protein
  - drug_effect
  - indication        # disease 
  - contraindication  # disease
  - off-label use     # disease

  # Gene/Protein-centric interactions & biology
  - protein_protein
  - bioprocess_protein
  - bioprocess_bioprocess
  - cellcomp_protein
  - cellcomp_cellcomp
  - molfunc_protein
  - molfunc_molfunc
  - pathway_protein
  - pathway_pathway

  # Anatomy
  - anatomy_anatomy
  - anatomy_protein_present
  - anatomy_protein_absent

  # Phenotype
  - phenotype_phenotype
  - phenotype_protein

  # Exposure
  - exposure_exposure
  - exposure_disease
  - exposure_protein
  - exposure_bioprocess
  - exposure_molfunc
  - exposure_cellcomp

node_types:
  - anatomy
  - biological_process
  - cellular_component
  - disease
  - drug
  - effect/phenotype
  - exposure
  - gene/protein
  - molecular_function
  - pathway