data_path: dataset_saves
dataset_config_path: dataset_config.yaml # configs/dataset/hpo_config.yaml

save:
  directory: dataset_gridsearch_results

# ezek lehet jók később ha d-p-re fókuszálunk
evaluation_entity_whitelist:
evaluation_relation_whitelist: disease_protein

# 2. Model
model: RotatE # TransE, RotatE, CompGCN, RGCN
model_kwargs:
  embedding_dim: 256
# 3. Loss
loss: MarginRankingLoss # MarginRankingLoss is the default, NSSALoss with larger margin can work eg. 10
loss_kwargs:
  margin: 1.0
# 4. Regularizer
# regularizer: lp
# regularizer_kwargs:
#   p: 3
#   weight: 0.0001
#   normalize: False
# 5. Optimizer
optimizer: Adam
optimizer_kwargs:
  lr: 0.001 # kicsit több? 0.005
clear_optimizer: False # False if want to continue training from checkpoint
# 5.1 Learning Rate Scheduler
lr_scheduler: ExponentialLR # CosineAnnealingLR?
lr_scheduler_kwargs:
  gamma: 0.9
# 6. Training Loop
training_loop: # slcwa or lcwa
training_loop_kwargs:
  # automatic_memory_optimization: False
negative_sampler: BasicNegativeSampler # BernoulliNegativeSampler, PseudoTypedNegativeSampler
negative_sampler_kwargs:
  num_negs_per_pos: 50
# 7. Training
epochs: 30
training_kwargs:
  batch_size: 1024
  checkpoint_name: checkpoint.pth
  # checkpoint_frequency: 10 # minutes
  checkpoint_on_failure: True
  # sampler: schlichtkrull
stopper: "early"
stopper_kwargs:
  frequency: 20
  patience: 1
  relative_delta: 0.005

# 8. Evaluation
evaluator: 
evaluator_kwargs:
evaluation_kwargs:
  batch_size: 2
# 9. Tracking
result_tracker: "wandb"
result_tracker_kwargs:
  project: DatasetGridSearch
  # tags: 
  #   - full_ds_with_inverse
  # reinit: finish_previous
# Misc
# metadata: 
# device: "cuda"
random_seed: 42
# use_testing_data: True
evaluation_fallback: False
# filter_validation_when_testing: True
use_tqdm: True
