kg_path: "primekg/kg.csv" # "primekg/kg_filtered.csv" # "primekg/kg.csv"
# label: 

key: "name" # "index" or "name"

drop_duplicates: True
remove_self_loops: True

inverse_relations: False # hpo nagyon lassú

# g-d (80k base) éleknek nagyjából 64-8-8k / 80-10-10%  vagy 72-4-4 ami 90-5-5% ???
val_count: 8000
test_count: 32000
random_seed: 42

# not working yet
features: 
#   enabled: True

relation_types:
  # Disease-centric
  - disease_disease
  - disease_protein
  - disease_phenotype_positive
  - disease_phenotype_negative

  # Drug-centric
  # - drug_drug
  - drug_protein
  - drug_effect
  - indication        # disease 
  - contraindication  # disease
  - off-label use     # disease

  # Gene/Protein-centric interactions & biology
  - protein_protein
  - bioprocess_protein
  - bioprocess_bioprocess
  - cellcomp_protein
  - cellcomp_cellcomp
  - molfunc_protein
  - molfunc_molfunc
  - pathway_protein
  - pathway_pathway

  # Anatomy
  - anatomy_anatomy
  # - anatomy_protein_present
  - anatomy_protein_absent

  # Phenotype
  - phenotype_phenotype
  - phenotype_protein

  # Exposure
  - exposure_exposure
  - exposure_disease
  - exposure_protein
  - exposure_bioprocess
  - exposure_molfunc
  - exposure_cellcomp

# leave out anatomy and drug for HPO bc they are too big
node_types:
  - disease
  - gene/protein
  - anatomy
  - biological_process
  - cellular_component
  - drug
  - effect/phenotype
  - exposure
  - molecular_function
  - pathway